import type { Metadata } from 'next';

export const SITE_ORIGIN = 'https://seokminshin.github.io';
export const SITE_BASE_PATH = '/portfolio';
export const SITE_URL = `${SITE_ORIGIN}${SITE_BASE_PATH}`;

export const SITE_TITLE = 'Seokmin Shin | Electrochemical Thermodynamics';
export const SITE_DESCRIPTION =
  'Research portfolio of Seokmin Shin — physical electrochemistry, electrochemical thermodynamics, and the driving forces behind interfacial charge transport.';

/**
 * The shared social card, generated by `npm run og` into public/og-card.png.
 *
 * Deliberately a plain asset with an absolute URL rather than Next's
 * `opengraph-image` file convention. That convention emits an extensionless
 * file under `output: export` (GitHub Pages then serves it as something other
 * than image/png), and it only reaches a page that does not declare its own
 * `openGraph` — declaring one replaces the parent's wholesale, so every inner
 * page silently lost its card.
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/og-card.png`,
  width: 1200,
  height: 630,
  alt: 'Seokmin Shin — Electrochemical Thermodynamics',
};

interface SocialOptions {
  title: string;
  description: string;
  /** Route path with leading and trailing slash, e.g. `/research/`. */
  path: string;
  type?: 'website' | 'article';
}

/** Open Graph and Twitter metadata for one page, card included. */
export function social({ title, description, path, type = 'website' }: SocialOptions): Metadata {
  return {
    openGraph: {
      type,
      siteName: 'Seokmin Shin',
      title,
      description,
      url: `${SITE_URL}${path}`,
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
