import type { Metadata } from 'next';
import { getPost, type Post } from '@/data/posts';

export const SITE_ORIGIN = 'https://seokminshin.github.io';
export const SITE_BASE_PATH = '/portfolio';
export const SITE_URL = `${SITE_ORIGIN}${SITE_BASE_PATH}`;

export const SITE_TITLE = 'Seokmin Shin | Electrochemical Thermodynamics';
export const SITE_DESCRIPTION =
  'Research portfolio of Seokmin Shin — physical electrochemistry, electrochemical thermodynamics, and the driving forces behind interfacial charge transport.';

export const CARD_SIZE = { width: 1200, height: 630 } as const;

interface OgImage {
  url: string;
  width: number;
  height: number;
  alt: string;
}

/**
 * The default social card, generated by `npm run og` into public/og-card.png.
 *
 * Deliberately a plain asset with an absolute URL rather than Next's
 * `opengraph-image` file convention. That convention emits an extensionless
 * file under `output: export` (GitHub Pages then serves it as something other
 * than image/png), and it only reaches a page that does not declare its own
 * `openGraph` — declaring one replaces the parent's wholesale, so every inner
 * page silently lost its card.
 */
export const OG_IMAGE: OgImage = {
  url: `${SITE_URL}/og-card.png`,
  width: CARD_SIZE.width,
  height: CARD_SIZE.height,
  alt: 'Seokmin Shin — Electrochemical Thermodynamics',
};

/**
 * Public path of one essay's own card, relative to the site root. The generator
 * in scripts/generate-og-image.mjs writes to the matching file under public/,
 * reading the same slugs from src/data/posts.ts — so a new essay gets a card
 * with no change here.
 */
export function postCardPath(slug: string): string {
  return `/og/${slug}.png`;
}

function postCardImage(post: Post): OgImage {
  return {
    url: `${SITE_URL}${postCardPath(post.slug)}`,
    width: CARD_SIZE.width,
    height: CARD_SIZE.height,
    alt: `${post.title} — Seokmin Shin`,
  };
}

interface SocialOptions {
  title: string;
  description: string;
  /** Route path with leading and trailing slash, e.g. `/research/`. */
  path: string;
  type?: 'website' | 'article';
  /** Defaults to the shared site card. */
  image?: OgImage;
}

/** Open Graph and Twitter metadata for one page, card included. */
export function social({
  title,
  description,
  path,
  type = 'website',
  image = OG_IMAGE,
}: SocialOptions): Metadata {
  return {
    openGraph: {
      type,
      siteName: 'Seokmin Shin',
      title,
      description,
      url: `${SITE_URL}${path}`,
      images: [image],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [image.url],
    },
  };
}

/**
 * Per-essay page metadata, derived from the single source of truth in
 * src/data/posts.ts. Lives here rather than beside the data so that
 * src/data/posts.ts stays free of runtime imports — the card generator is a
 * plain Node script and imports that file directly.
 */
export function postMetadata(slug: string): Metadata {
  const post = getPost(slug);
  return {
    title: post.title,
    description: post.excerpt,
    ...social({
      title: post.title,
      description: post.excerpt,
      path: `/posts/${post.slug}/`,
      type: 'article',
      image: postCardImage(post),
    }),
  };
}
